### PR TITLE
add label to variables

### PR DESCRIPTION
**Pull request by lagartoverde**
https://binnenland.atlassian.net/browse/GN-4298

### CODE REVIEW

**Review by x-m-el — CHANGES_REQUESTED** [review]
Some testing that popped up problems:
- I can't edit a label of a variable after it has been inserted (the box for the variable doesn't pop up so I can't edit it at all, except for typing in it). I don't see this mentioned in the design though. So maybe this functionality is not needed. However I do see code for it in `updateVariableLabel` so I'd guess you are supposed to :shrug: 
- `When the user clicks on the pill to fill in the variable, the cursor will set itself in front of the brackets with the label, which is where the user can start typing (unless otherwise stated, like with the number variable)` of the design is not implemented. You can get to this state by inserting a variable and deleting the placeholder text (type something and then delete everything). It becomes really hard to type in the variable now. As the design mentions, clicking on the label-part of the variable should also place the cursor inside the variable text input.
- The variable text takes the same size as the text it surrounds. E.g. adding a variable in a h1 (koptitel 1) heading will create a variable with the label being really big. For me this is not the main problem. The problem is that the variable input (or the text of the variable itself) doesn't scale. so it looks really weird and ugly. Because the input of a variable is an embbeded prosemirror instance (I think?) just fixing the scaling of the variable label is probably the easiest option.


I am not sure how I should test that the labels get "saved" properly (that `toDOM` and `parseDOM` are configured correctly). Looking at the code it looks correct, but is there anyway to actually test this (easily)?

**Comment by abeforgit** [comment]
@x-m-el your last question has a easy answer: you can use the "show export preview" button in the dummy app

**Comment by x-m-el** [comment]
> @x-m-el your last question has a easy answer: you can use the "show export preview" button in the dummy app

And using "customHTML" to import it back to check if parseDOM works. I knew about both, didn't think about using them in sequence to test :)

**Comment by lagartoverde** [comment]
Now depends on https://github.com/lblod/ember-rdfa-editor/pull/801

**Review by x-m-el — COMMENTED** [review]
1.   A label is still big inside a header/the value is still small inside a header:
afbeelding
2. still can't edit a variable's label once it has been inserted (but maybe this is not needed, as users can just remove and recreate it?)
3. Clicking on a variable label doesn't seem to work perfectly yet. When having empty text like this:
afbeelding
I can only get inside the space to edit the text of the variable by using arrow-keys. Nothing with the mouse seems to put my cursor in the correct place. Clicking on the label itself also doesn't do this. I can select the label text, but it is supposed to instead go inside the place to edit the variable, not select the label's text.

4. label does not show up for a date variable.

**Review by x-m-el — CHANGES_REQUESTED** [review]
see above changes for actual review (making a review here so you can hopefully re-request a review from me after you fixed stuff).

**Comment by lagartoverde** [comment]
I solved the problem with inserting variables in a heading, I'm not really happy with that, but I think is not in the scope of this PR, I will comment it with arne in the standup and will create another ticket for it, as an inner editor should pick all the marks from the outer editor

**Comment by abeforgit** [comment]
> It looks like if you run `npm run lint:fix` locally it will fail. Woodpecker seems to be picking up eslint cache or something and not failing.

note woodpecker runs `lint:js` and `lint:hbs`, not `lint:fix`

**Review by x-m-el — CHANGES_REQUESTED** [review]
afbeelding
Weirdly enough, the value does show big for dates... However, we'll keep that for a different issue: [GN-4347](https://binnenland.atlassian.net/browse/GN-4347)

Can't edit a variable's label after it was created, but that's kinda related to [GN-4346](https://binnenland.atlassian.net/browse/GN-4346). So we can ignore this for now, because it is not yet clear if and how we'd want to do this.

I think that if you import an old document, the labels won't show up. Would make sense for the "default label" to automatically show up by the parsing (so changing `parseDOM` to show a default label if one wasn't specified in attribute `dataLabel`). I am not sure how feasible this is. This will only happen for old documents (new ones will always have the label in the html). So it is maybe a question of how many documents/templates there are that won't have this label because of this.

- [ ] BUG: the date variable is broken :(  The buttons to change the format don't work anymore.

**Review by x-m-el — APPROVED** [review]
- bug with dates fixed
- old variables now also have date
- no other issues found: 
  - tested insert variables and dates 
  - tried to break date plugin, but kept working :)
  
Good to merge.

**Pull request merged**
