### PR TITLE
Only show title annotations in the actual document

### PR DESCRIPTION
**Pull request by lagartoverde**
### Overview
I linked the title annotation to the rdfa-annotations-hover class so it only shows in the actual document and not in any of the exported versions, I see that we removed the rdfa-annotations class so maybe we don't want any of the annotations. In this case we can just remove this code, let me know

##### connected issues and PRs:
GN-4960

### Setup
Link to frontend

### How to test/reproduce
then create a meeting with a besluit in it, see that the title annotation now is not shown in any of the html forms of the agendapoint

### Challenges/uncertainties
As I said we might not want to show this annotation at all

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check if dummy app is correctly updated
- [x] Check cancel/go-back flows
- [x] changelog
- [x] npm lint
- [x] no new deprecations

### CODE REVIEW

**Review by elpoelma — COMMENTED** [review]
Two things to note:
- I think it's indeed better to drop the annotations, as we do not seem to use them anymore (and I think our users do not either).
- While testing this PR (in GN), I noticed the `heading` node does not seem to be converted to the rdfa-aware version yet, I'll adjust this in a seperate PR.

**Comment by abeforgit** [comment]
>     * I think it's indeed better to drop the annotations, as we do not seem to use them anymore (and I think our users do not either).

Yes, but not in this PR
The PMs seem a bit attached to this feature, we shouldn't randomly drop it

**Comment by abeforgit** [comment]
@elpoelma 
> While testing this PR (in GN), I noticed the heading node does not seem to be converted to the rdfa-aware version yet, I'll adjust this in a seperate PR.

can you clarify what this means for this PR? does it block the merge?

**Comment by abeforgit** [comment]
@lagartoverde 
so this is a pretty typical PR for our team, it's a good opportunity to practice best practices for prs

- you need to start the CI pipelines
- the "release-commit" pipeline will make a dev version available in npm
- you should make a PR in the frontends that bumps to that version
this has 2 advantages: 
  - much easier to test (we can just npm install in the frontends)
  - you don't forget that the work is not done until it's merged in the app upstream
  
 once you merge this PR:
 - you should make a release
 - you should bump your frontend PRs to the new "real" release (if they've been approved at that point, you can merge, no need to wait)
 - make frontend releases
 - bump the frontend in the app repos (no need for a PR, but you should add a changeset so it updates the changelog)
 - release the app repos
 - update the "released in" fields of the jira ticket
 - move the ticket to "gereed (dev)" if all target apps have a release

**Comment by elpoelma** [comment]
> @elpoelma
> 
> > While testing this PR (in GN), I noticed the heading node does not seem to be converted to the rdfa-aware version yet, I'll adjust this in a seperate PR.
> 
> can you clarify what this means for this PR? does it block the merge?

No it doesn't block this merge, it's a PR on the GN repo, specifically https://github.com/lblod/frontend-gelinkt-notuleren/pull/699

**Comment by lagartoverde** [comment]
https://github.com/lblod/frontend-gelinkt-notuleren/pull/701 Can test the frontend with this PR

**Review by elpoelma — APPROVED** [review]

**Pull request merged**
