### PR TITLE
GN-4502: allow municipality and street field of address plugin to be cleared

### PR DESCRIPTION
**Pull request by elpoelma**
### Overview
This PR ensures that users are able to clear the municipality and street inputs when editing an address variable. This is implemented by passing the `allowClear` argument to the `power-select` components.

##### connected issues and PRs:
[GN-4502](https://binnenland.atlassian.net/browse/GN-4502?atlOrigin=eyJpIjoiMzRhYzI1NjI3Nzc3NDQ3M2I3ZDkyMjVkZTcyZDIwYjIiLCJwIjoiaiJ9)

### How to test/reproduce
- Insert an address variable and select it
- Notice that when the street/municipality fields are filled out, you can clear their value
- When clearing the street input, the housenumber and busnumber fields should also be cleared
- When clearing the municipality input, all other fields should also be cleared

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check if dummy app is correctly updated
- [x] changelog
- [x] npm lint
- [x] no new deprecations

### CODE REVIEW

**Review by x-m-el — APPROVED** [review]
small bug
1. open the street select
2. now click on the "clear city" cross
3. select of street will still be highlighted (blue border), but disabled.
Not sure if the problem comes from powerselect and if it is fixable. But maybe you can hook into the clearing and deselect it or change the css so it doesn't hightlight something disabled? 
Problem does not occur for the text inputs.

No other issues I could find :)

**Comment by elpoelma** [comment]
> small bug
> 
>     1. open the street select
> 
>     2. now click on the "clear city" cross
> 
>     3. select of street will still be highlighted (blue border), but disabled.
>        Not sure if the problem comes from powerselect and if it is fixable. But maybe you can hook into the clearing and deselect it or change the css so it doesn't hightlight something disabled?
>        Problem does not occur for the text inputs.
> 
> 
> No other issues I could find :)

I think we can classify this as a power-select bug, as the `ember-power-select-trigger--active` class is not removed when the select-element is disabled. We could indeed fix it with css, I don't know if it is fixed in the latest release of `power-select` (7.x.x)

**Comment by elpoelma** [comment]
> > small bug
> > ```
> > 1. open the street select
> > 
> > 2. now click on the "clear city" cross
> > 
> > 3. select of street will still be highlighted (blue border), but disabled.
> >    Not sure if the problem comes from powerselect and if it is fixable. But maybe you can hook into the clearing and deselect it or change the css so it doesn't hightlight something disabled?
> >    Problem does not occur for the text inputs.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > No other issues I could find :)
> 
> I think we can classify this as a power-select bug, as the `ember-power-select-trigger--active` class is not removed when the select-element is disabled. We could indeed fix it with css, I don't know if it is fixed in the latest release of `power-select` (7.x.x)

It does not seem to be fixed in the latest 7.x release. I could open an issue on appuniversum, to not apply the blue border style when the input is disabled.

**Comment by x-m-el** [comment]
Issue on AU makes sense (and more chance it'll actually get fixed).
It's not a breaking thing so I think that's good enough. At least it'll be fixed sometime in the future then :)

Could add a comment to the code linking to the issue, so it is obvious the bug is known and isn't researched uselessly in the future.

**Comment by elpoelma** [comment]
> Issue on AU makes sense (and more chance it'll actually get fixed). It's not a breaking thing so I think that's good enough. At least it'll be fixed sometime in the future then :)
> 
> Could add a comment to the code linking to the issue, so it is obvious the bug is known and isn't researched uselessly in the future.

I submitted an issue: https://github.com/appuniversum/ember-appuniversum/issues/439. I did notice it is not an issue on chromium-based browsers. So the fact that the class is not removed/the input-component is not deselected could be a firefox bug.

**Pull request merged**
