### PR TITLE
GN-4444: Insert snippet first node correctly

### PR DESCRIPTION
**Pull request by dkozickis**
First node of the snippet still was not inserted correctly.

Inserting bunch of `Node`s with `replaceSelectionWith` is worse than inserting `Slice` with `replaceSelection`. As also evident, by the fact that `replaceSelection` is used in other places, not `replaceSelectionWith`.

https://binnenland.atlassian.net/browse/GN-4444

### CODE REVIEW

**Comment by elpoelma** [comment]
I'm not really able to reproduce the issue where the first node is not inserted correctly. Could you give me an example?

**Comment by abeforgit** [comment]
> Inserting bunch of Nodes with replaceSelectionWith is worse than inserting Slice with replaceSelection.

in what way? are there performance issues or something?

**Comment by elpoelma** [comment]
> Note the first node is not correct
> 
> **Before**
> 
>  CleanShot.2023-08-03.at.18.04.59.mp4 
> **After**
> 
>  CleanShot.2023-08-03.at.18.05.38.mp4

Aha ok I understand I think. In the first video an empty paragraph is inserted before the snippet, and as paragraphs (or other nodes besides a table of contents) are not allowed before document-titles, prosemirror just tries it best with the document-title. In the second there is no such issue, as no empty paragraph is inserted before the document-title.

But anyway, this is normal behaviour. Some nodes included in a snippet document will not be able to be inserted at the location where you want to insert the snippet.

**Comment by elpoelma** [comment]
> > > Note the first node is not correct
> > > **Before**
> > > CleanShot.2023-08-03.at.18.04.59.mp4
> > > **After**
> > > CleanShot.2023-08-03.at.18.05.38.mp4
> > 
> > 
> > Aha ok I understand I think. In the first video an empty paragraph is inserted before the snippet, and as paragraphs (or other nodes besides a table of contents) are not allowed before document-titles, prosemirror just tries it best with the document-title. In the second there is no such issue, as no empty paragraph is inserted before the document-title.
> > But anyway, this is normal behaviour. Some nodes included in a snippet document will not be able to be inserted at the location where you want to insert the snippet.
> 
> But still, I'm inserting a snippet with document title at the start of the document, might as well get it inserted correctly? thinking

I agree.

**Review by elpoelma — APPROVED** [review]

**Pull request merged**
