### PR TITLE
small citation plugin fixes 

### PR DESCRIPTION
**Pull request by abeforgit**
### Overview

started by looking into that weird `htmlsafe` import, but also found a bunch of small problems

- fix(i18n): fix typo
- fix(citation): add missing argument to citation card in dummy app
- fix(citation): remove the unnecessary type and add the html-safe tag at the rendering site
- fix(citation): correct erroneous arguments to AuAlert

##### connected issues and PRs:

relates to #159 

### How to test/reproduce

citations without articles now show a proper message instead of an empty square
the citation sidebar card actually works now on the dummy app

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check if dummy app is correctly updated
- [x] Check cancel/go-back flows
- [x] changelog
- [x] npm lint
- [x] no new deprecations

### CODE REVIEW

**Review by lagartoverde — APPROVED** [review]
Looks good to me, good improvements 👍

**Comment by x-m-el** [comment]
When searching for citations and nothing is found, there is still a grey box:
image
Not really part of what you fixed, but as you made some error UI changes, might be an idea to fix this too.

I couldn't test the case of no articles, because I don't know which citation has no articles :)

**Review by x-m-el — COMMENTED** [review]
When searching for citations and nothing is found, there is still a grey box:
image
Not really part of what you fixed, but as you made some error UI changes, might be an idea to fix this too.

I couldn't test the case of no articles, because I don't know which citation has no articles :)

**Comment by abeforgit** [comment]
@x-m-el not sure what's going wrong on your end but here it renders correctly?
image

**Comment by x-m-el** [comment]
> @x-m-el not sure what's going wrong on your end but here it renders correctly? image

Yes, my bad. Probably wrong branch or something :)

approved :+1:

**Pull request merged**
