### PR TITLE
GN-4370: Allow block content in `article_paragraph`

### PR DESCRIPTION
**Pull request by dkozickis**
### Overview

Allows to insert `inline*` content in `article_paragraph`, that helps insert `table` among other stuff.

#### Connected issues and PRs:

https://binnenland.atlassian.net/browse/GN-4370

### Setup

1. Checkout
2. `npm run start`

### How to test/reproduce

Observe that it is not possible to reproduce issue with inserting table in article paragraph described in https://binnenland.atlassian.net/browse/GN-4370, this does not stop from inserting table into other article nodes, the fix is implemented in `embed-rdfa-editor` MR https://github.com/lblod/ember-rdfa-editor/pull/911

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check if dummy app is correctly updated
- [x] Check cancel/go-back flows
- [x] changelog
- [x] npm lint
- [x] no new deprecations

### CODE REVIEW

**Review by elpoelma — CHANGES_REQUESTED** [review]
Shouldn't this be `block*` as the table is a block node and paragraphs are too?

**Comment by elpoelma** [comment]
> > Shouldn't this be `block*` as the table is a block node and paragraphs are too?
> 
> The "usual" paragraph is `inline*` 🤔 - https://github.com/lblod/ember-rdfa-editor/blob/b477fdba7bc5aaf08777515465f285066e0e5367/addon/nodes/paragraph.ts#L15

yeah but this is not a paragraph in the sense of a `p` tag. It is just called a `paragraph` but should allow any content.

**Comment by x-m-el** [comment]
This is probably a valid solution, but the places where this paragraph is supported is artikel, which has as content `'(block|article_paragraph)+'`.
Which says to put block things before/after paragraphs.

But tbh, it makes more sense to put everything inside article_paragraphs (because that's the reason this structure exists???), so allowing block content in it feels like a good change.

**Review by elpoelma — APPROVED** [review]
Looks good!

**Pull request merged**
