### PR TITLE
Remove label when variable is filled

### PR DESCRIPTION
**Pull request by lagartoverde**
### Overview
I made so the label is not shown when you fill a variable

##### connected issues and PRs:
GN-4824

### How to test/reproduce
You can insert one of each variables and fill it, appreciate that the label is indeed hidden, in some variables you can go back to an unfilled status, and the variable should reappear, but on others this is just not possible because of how the variable UI is made

### Checks PR readiness
- [x] UI: works on smaller screen sizes
- [x] UI: feedback for any loading/error states
- [x] Check if dummy app is correctly updated
- [x] Check cancel/go-back flows
- [x] changelog
- [x] npm lint
- [x] no new deprecations

### CODE REVIEW

**Comment by lagartoverde** [comment]
The thinner version works with all of them, and I think is prefered, what I did now is to make it consistent, as some variable were 25px and some 29px, so I set all of them at 30px.
So we will have with label 35px and without 30px, I don't know is this is correct or I should make them all 35. Maybe @abeforgit can throw some light

**Comment by elpoelma** [comment]
> The thinner version works with all of them, and I think is prefered, what I did now is to make it consistent, as some variable were 25px and some 29px, so I set all of them at 30px. So we will have with label 35px and without 30px, I don't know is this is correct or I should make them all 35. Maybe @abeforgit can throw some light

IMO we should probably use the same height whether a label is shown or not. This shows the user that they are handling the same type of data.

**Comment by piemonkey** [comment]
For me, I think thinner is better, as it reduces the impact of adding a variable to the rest of the layout. I think the most important thing is that they don't change size though, as it means the layout changes just by adding content, which to me would indicate that the type of node is changing.

**Comment by lagartoverde** [comment]
You can review this again

**Review by piemonkey — APPROVED** [review]

**Pull request merged**
