### PR TITLE
GN-4365: add optional internationalization support to static version of table of contents

### PR DESCRIPTION
**Pull request by elpoelma**
### Overview
This PR adds internationalization support to the static version of the table-of-contents node. When constructing the table_of_contents nodespec and nodeview, an optional `intl: IntlService` argument can be provided.

##### connected issues and PRs:
Jira: https://binnenland.atlassian.net/browse/GN-4365?atlOrigin=eyJpIjoiZmI3OWExMWQ1Mzc5NGUzN2FiOTA0MjUwMmJmNTQzM2MiLCJwIjoiaiJ9

### How to test/reproduce
Enable the table-of-contents node on the regulatory statements dummy route and check if the static version is correctly internationalized.

### Challenges/uncertainties
- I'm not completely sure about the interface, the main issue I'm trying to solve is giving access to ember-intl to the `toDOM` node-spec method.

### Checks PR readiness
- [x] changelog
- [x] npm lint

### CODE REVIEW

**Review by x-m-el — COMMENTED** [review]
-- not review, just a note! --
Maybe I'm missing something, but wouldn't the TOC use the localePlugin from https://github.com/lblod/ember-rdfa-editor/pull/857 to choose what language to show?
This is more general, as the user can choose exactly which text to choose in which context. The main problem I see is the inconsistency: the documentlanguage (via localPlugin) might be different from the language that `intl` will get.

**Comment by elpoelma** [comment]
> -- not review, just a note! -- Maybe I'm missing something, but wouldn't the TOC use the localePlugin from [lblod/ember-rdfa-editor#857](https://github.com/lblod/ember-rdfa-editor/pull/857) to choose what language to show? This is more general, as the user can choose exactly which text to choose in which context. The main problem I see is the inconsistency: the documentlanguage (via localPlugin) might be different from the language that `intl` will get.

Indeed, but I'm also hesitating because of the inconsistency, maybe it's better to just use the language `ember-intl` gets.

**Comment by elpoelma** [comment]
I will update this PR once I finished up the PR for document language support on the editor.

**Comment by elpoelma** [comment]
> this depends on the document language right? if so, you need to bump the peerdep before merging

Indeed, but I'll update this PR once I have a custom serializer working.

**Pull request closed without merging**
